<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/VV.Master" Culture="en-IN" CodeBehind="PrimaryBoxEntryMaintenance.aspx.cs" Inherits="VV.PrimaryBoxEntryManitance" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <script language="javascript" type="text/javascript">
        function OpenWindowForSticker() {
            window.open("PrimaryBoxNoForPrint.aspx");
        }
        function OpenWindowForDocPageOne() {
            window.open("DocPageOne.aspx");
        }
        function OpenWindowForDocPageTwo() {
            window.open("DocPageTwo.aspx");
        }
        function OpenWindowForDocPageThree() {
            window.open("DocPageThree.aspx");
        }
    </script>

    <link href="CSS/Main.css" rel="stylesheet" />
    

    <table style="height: 100%;" width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="left" class="secondLevelHeader" width="15%">
                <asp:Label ID="lblPageTitle" runat="server" Text="Primary Box Edit" />
            </td>

            <td width="75%" align="right" style="padding-left: 200px;" class="secondLevelHeader">
                <asp:Panel ID="SearchPanel" DefaultButton="btnSearchBox" runat="server">
                    <asp:Label ID="lblProdOrderNo" style="font-weight:100" Text="Prod Order No" runat="server"></asp:Label>
                    &nbsp;
                    <asp:TextBox ID="txtProdOrderNo" runat="server" ToolTip="Enter Prod Order No to be Searched" onKeyUp="ControlSearch(this)" />
                    <asp:Button ID="btnSearchBox" runat="server" Text="Search" OnClick="btnSearchBox_Click"
                        ToolTip="Click to Search Data" CssClass="buttonText" Enabled="true" />
                </asp:Panel>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <%--Added by Arun on 26-Dec'07.
                 Implemeted the Update Panel, so as to avoid showing the flickering, when any operations are done --%>
                <asp:ScriptManager ID="ScriptManager1" runat="server" />
                <asp:UpdatePanel ID="EmployeePanel" UpdateMode="always" runat="server">
                    <%--<Triggers>
                        <asp:AsyncPostBackTrigger />
                    </Triggers>--%>
                    <ContentTemplate>
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                            OnRowCancelingEdit="GridView1_RowCancelingEdit" PageSize="30" OnRowEditing="GridView1_RowEditing" OnRowDataBound="GridView1_RowDataBound" OnRowUpdating="GridView1_RowUpdating" CssClass="Grid" HeaderStyle-CssClass="Grid_Header"
                            PagerStyle-CssClass="Grid_Pager" OnRowDeleting="GridView1_RowDeleting" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" RowStyle-CssClass="Grid_Record" AlternatingRowStyle-CssClass="Grid_Alternate_Record" EmptyDataText="No Records To Display"
                            CellPadding="3">
                            <Columns>

                                <asp:TemplateField HeaderText="Prod Order No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblProdOrderNo" runat="server" Text='<%# Eval("ProdOrderNo") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Primary Box No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblPrimaryBoxNo" runat="server" Text='<%# Eval("PrimaryBoxNo") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Box Date">
                                    <ItemTemplate>
                                        <asp:Label ID="lblBoxDate" runat="server" Text='<%# Eval("BoxDate") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Primary Box Qty">
                                    <ItemTemplate>
                                        <asp:Label runat="server" ID="lblPrimaryBoxQty" Text='<%# Eval("PrimaryBoxQty") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="OrderNum">
                                    <ItemTemplate>
                                        <asp:Label ID="lblOrderNum" runat="server" Text='<%# Eval("OrderNum") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Pos">
                                    <ItemTemplate>
                                        <asp:Label ID="lblPos" runat="server" Text='<%# Eval("Pos") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                    <%--                                    <ItemStyle Width="100px" />
                                    <HeaderStyle Width="100px" />--%>
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Item">
                                    <ItemTemplate>
                                        <asp:Label ID="lblItem" runat="server" Text='<%# Eval("Item") %>'></asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Body Heat No">
                                    <ItemTemplate>
                                        <asp:TextBox ID="txtBodyHeatNo" runat="server" Enabled="true" Text='<%# Bind("BodyHeatNo") %>'> </asp:TextBox>
                                   </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Bonnet Heat No">
                                    <ItemTemplate>
                                        <asp:TextBox ID="txtBonnetHeatNo" runat="server" Enabled="true" Text='<%# Bind("BonnetHeatNo") %>'> </asp:TextBox>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Drg No">
                                    <ItemTemplate>
                                        <asp:TextBox ID="txtDrgNo" runat="server" Enabled="true" Text='<%# Bind("DrgNo") %>'> </asp:TextBox>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Tag No">
                                    <ItemTemplate>
                                        <asp:TextBox ID="txtTagNo" runat="server" Enabled="true" Text='<%# Bind("TagNo") %>'> </asp:TextBox>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="" Visible="true">
                            <ItemTemplate>
                                <asp:Button ID="BtnPrint" runat="server" Text="Sticker"
                                    OnClick="BtnPrint_Click" OnClientClick="OpenWindowForSticker()"/>
                                <input id="hidPrimaryBoxNo" value='<%# Eval("PrimaryBoxNo") %>' type="hidden" runat="server" />
                            </ItemTemplate>
                            <ItemStyle Wrap="false" />
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="" Visible="true">
                            <ItemTemplate>
                                <asp:Button ID="BtnDocPage1" runat="server" Text="DOCPage1"
                                    OnClick="BtnDocPage1_Click" OnClientClick="OpenWindowForDocPageOne()"/>
                                <input id="hidPrimaryBoxNoDocPage1" value='<%# Eval("PrimaryBoxNo") %>' type="hidden" runat="server" />
                            </ItemTemplate>
                            <ItemStyle Wrap="false" />
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="" Visible="true">
                            <ItemTemplate>
                                <asp:Button ID="BtnDOCPage2" runat="server" Text="DOCPage2"
                                    OnClick="BtnDOCPage2_Click" OnClientClick="OpenWindowForDocPageTwo()"/>
                                <input id="hidPrimaryBoxNoDocPage2" value='<%# Eval("PrimaryBoxNo") %>' type="hidden" runat="server" />
                            </ItemTemplate>
                            <ItemStyle Wrap="false" />
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="" Visible="true">
                            <ItemTemplate>
                                <asp:Button ID="BtnDocPage3" runat="server" Text="DOCPage3"
                                    OnClick="BtnDocPage3_Click" OnClientClick="OpenWindowForDocPageThree()"/>
                                <input id="hidPrimaryBoxNoDocPage3" value='<%# Eval("PrimaryBoxNo") %>' type="hidden" runat="server" />
                            </ItemTemplate>
                            <ItemStyle Wrap="false" />
                        </asp:TemplateField>

                                
                            </Columns>

                            <HeaderStyle CssClass="Grid_Header" />
                            <FooterStyle CssClass="Grid_Summary" />
                            <PagerStyle CssClass="Grid_Pager" />
                            <EmptyDataRowStyle CssClass="EmptyCell" />
                            <RowStyle CssClass="Grid_Record" />
                            <AlternatingRowStyle CssClass="Grid_Alternate_Record" />
                            <SelectedRowStyle BackColor="#FFEEC2" />
                            <PagerSettings Position="TopAndBottom" />

                        </asp:GridView>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
        </tr>
    </table>
</asp:Content>
