<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/VV.Master" Culture="en-IN" CodeBehind="SecondaryBoxMaintenance.aspx.cs" Inherits="VV.WebForm2" %>


<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <link href="CSS/Main.css" rel="stylesheet" />

    <table style="height: 100%;" width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="left" class="secondLevelHeader" width="15%">
                <asp:Label ID="lblPageTitle" runat="server" Text="Secondary Box Edit" />
            </td>

            <td width="75%" align="right" style="padding-left: 200px;" class="secondLevelHeader">
                <asp:Panel ID="SearchPanel" DefaultButton="btnSearchBox" runat="server">
                    <asp:Label ID="lblSecondaryBoxNo" style="font-weight:100" Text="Secondary Box No" runat="server"></asp:Label>
                    &nbsp;
                    <asp:TextBox ID="txtSecondaryBoxNo" runat="server" ToolTip="Enter Secondary Box no to be Searched" onKeyUp="ControlSearch(this)" />
                    <asp:Button ID="btnSearchBox" runat="server" Text="Search" OnClick="btnSearchBox_Click"
                        ToolTip="Click to Search Data" CssClass="buttonText" Enabled="true" />
                </asp:Panel>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <%--Added by Arun on 26-Dec'07.
                 Implemeted the Update Panel, so as to avoid showing the flickering, when any operations are done --%>
                <asp:ScriptManager ID="ScriptManager1" runat="server" />
                <asp:UpdatePanel ID="EmployeePanel" UpdateMode="always" runat="server">
                    <%--<Triggers>
                        <asp:AsyncPostBackTrigger />
                    </Triggers>--%>
                    <ContentTemplate>
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
                            OnRowCancelingEdit="GridView1_RowCancelingEdit" PageSize="30" OnRowDataBound="GridView1_RowDataBound" CssClass="Grid" HeaderStyle-CssClass="Grid_Header"
                            PagerStyle-CssClass="Grid_Pager" OnRowDeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="true" RowStyle-CssClass="Grid_Record" AlternatingRowStyle-CssClass="Grid_Alternate_Record" EmptyDataText="No Records To Display"
                            CellPadding="3">
                            <Columns>
                                <asp:TemplateField HeaderText="Secondary Box No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblSecondaryBoxNo" runat="server" Text='<%# Eval("SecondaryBoxNo") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Box Date">
                                    <ItemTemplate>
                                        <asp:Label ID="lblBoxDate" runat="server" Text='<%# Eval("BoxDate") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Prod Order No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblProdOrderNo" runat="server" Text='<%# Eval("ProdOrderNo") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Primary Box No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblPrimaryBoxNo" runat="server" Text='<%# Eval("PrimaryBoxNo") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>


                                <asp:TemplateField HeaderText="Primary Box Qty">
                                    <ItemTemplate>
                                        <asp:Label runat="server" ID="lblPrimaryBoxQty" Text='<%# Eval("PrimaryBoxQty") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="OrderNum">
                                    <ItemTemplate>
                                        <asp:Label ID="lblOrderNum" runat="server" Text='<%# Eval("OrderNum") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Pos">
                                    <ItemTemplate>
                                        <asp:Label ID="lblPos" runat="server" Text='<%# Eval("Pos") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                    <%--                                    <ItemStyle Width="100px" />
                                    <HeaderStyle Width="100px" />--%>
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Item">
                                    <ItemTemplate>
                                        <asp:Label ID="lblItem" runat="server" Text='<%# Eval("Item") %>'></asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Body Heat No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblBodyHeatNo" runat="server" Text='<%# Eval("BodyHeatNo") %>'></asp:Label>
                                   </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Bonnet Heat No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblBonnetHeatNo" runat="server" Text='<%# Eval("BonnetHeatNo") %>'></asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Drg No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblDrgNo" runat="server" Text='<%# Eval("DrgNo") %>'></asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Tag No">
                                    <ItemTemplate>
                                        <asp:Label ID="lblTagNo" runat="server" Text='<%# Eval("TagNo") %>'></asp:Label>
                                    </ItemTemplate>
                                    <ItemStyle Wrap="false" />
                                </asp:TemplateField>

                            </Columns>

                            <HeaderStyle CssClass="Grid_Header" />
                            <FooterStyle CssClass="Grid_Summary" />
                            <PagerStyle CssClass="Grid_Pager" />
                            <EmptyDataRowStyle CssClass="EmptyCell" />
                            <RowStyle CssClass="Grid_Record" />
                            <AlternatingRowStyle CssClass="Grid_Alternate_Record" />
                            <SelectedRowStyle BackColor="#FFEEC2" />
                            <PagerSettings Position="TopAndBottom" />

                        </asp:GridView>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
        </tr>
    </table>
</asp:Content>
